### ISSUE TITLE
Erro na instalação dos requirements no venv

### ISSUE THREAD

**Issue by Mazuh** [yuriscosta/planilha_amortizacao#3]
Rodei todos os comandos normalmente. Até que um erro surgiu no meu Xubuntu 17.

Rodando o comando:
> (venv) mazuh@mazuh-n4050:~/Projects/planilha_amortizacao$ pip install -r requirements.txt

A saída é:
> Collecting cairocffi==0.8.0 (from -r requirements.txt (line 1))
>   Downloading cairocffi-0.8.0.tar.gz (79kB)
>     100% |████████████████████████████████| 81kB 358kB/s 
>     Complete output from command python setup.py egg_info:
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
>      #include <ffi.h>
>                      ^
>     compilation terminated.
>     Traceback (most recent call last):
>       File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
>         extra_postargs)
>       File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
>         spawn(cmd, dry_run=self.dry_run)
>       File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
>         _spawn_posix(cmd, search_path, dry_run=dry_run)
>       File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
>         % (cmd, exit_status))
>     distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
>         cmd = self.call_command('install_lib', warn_dir=0)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
>         self.run_command(cmdname)
>       File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
>         self.build()
>       File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
>         self.run_command('build_ext')
>       File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
>         _build_ext.run(self)
>       File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
>         self._build_extensions_serial()
>       File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
>         self.build_extension(ext)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
>         _build_ext.build_extension(self, ext)
>       File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
>         depends=ext.depends)
>       File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
>         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
>       File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
>         raise CompileError(msg)
>     distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
>         yield saved
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
>         yield
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
>         _execfile(setup_script, ns)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
>         exec(code, globals, locals)
>       File "/tmp/easy_install-fhzgb3ev/cffi-1.10.0/setup.py", line 232, in <module>
>       File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
>         raise SystemExit("error: " + str(msg))
>     SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
>         run_setup(setup_script, args)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 257, in run_setup
>         raise
>       File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
>         yield
>       File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 170, in save_modules
>         saved_exc.resume()
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 145, in resume
>         six.reraise(type, exc, self._tb)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
>         raise value.with_traceback(tb)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
>         yield saved
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
>         yield
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
>         _execfile(setup_script, ns)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
>         exec(code, globals, locals)
>       File "/tmp/easy_install-fhzgb3ev/cffi-1.10.0/setup.py", line 232, in <module>
>       File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
>         raise SystemExit("error: " + str(msg))
>     SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-se8pjqaf/cairocffi/setup.py", line 44, in <module>
>         extras_require={'xcb': ['xcffib>=0.3.2']},
>       File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/dist.py", line 336, in __init__
>         self.fetch_build_eggs(attrs['setup_requires'])
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/dist.py", line 419, in fetch_build_eggs
>         replace_conflicting=True,
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
>         dist = best[req.key] = env.best_match(req, ws, installer)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1126, in best_match
>         return self.obtain(req, installer)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1138, in obtain
>         return installer(requirement)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/dist.py", line 491, in fetch_build_egg
>         return cmd.easy_install(req)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
>         return self.install_item(spec, dist.location, tmpdir, deps)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 698, in install_item
>         dists = self.install_eggs(spec, download, tmpdir)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
>         return self.build_and_install(setup_script, setup_base)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
>         self.run_setup(setup_script, setup_base, args)
>       File "/home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
>         raise DistutilsError("Setup script exited with %s" % (v.args[0],))
>     distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-se8pjqaf/cairocffi/

Imediatamente após isso executei os outros seguintes comandos ainda dentro do ```venv```:

```python --version```
> Python 3.5.3

```virtualenv --version```
> 15.1.0

```pip --version```
> pip 9.0.1 from /home/mazuh/Projects/planilha_amortizacao/venv/lib/python3.5/site-packages (python 3.5)

Tentando rodar ```python ./main.py``` resulta em erro de "no module named 'weasyprint'".

**Comment by Mazuh** [comment]
Se não souber o que é e tiver com preguiça de rodar numa máquina virtual, tenta escrever um Dockerfile. Como é só um python sem dependências fica easy easy. Algo como:

```Dockerfile
FROM python:3.5
ADD . /planilha_amortizacao
WORKDIR /planilha_amortizacao
RUN pip install -r requirements.txt
```

Isso no mesmo diretório do requirements.txt vai, ao rodar um ```docker build```, irá:
- Baixar a imagem do Python direto do Dockerhub, que é fornecida pelos próprios desenvolvedores core do Python
- Associar o local atual (por isso o ponto ```.```) (repare que tem um espaço após ele) a um container que terá uma "pasta" chamada ```/planilha_amortizacao``` dentro dele.
- Irá mandar o Docker entrar nessa "pasta" (que, repetindo, é uma espécie de alias pra o diretório atual)
- Irá rodar os requirements.

Além dos comandos acima, creio que seja necessário adicionar mais uma linha ao Dockerfile: ```RUN main.py``` pra já rodar após o build.

Pra mais detalhes, acho que o Dockerhub dessa imagem aí deve ter mais instruções.
